# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'
    arguments: '--build-arg PAT=$(System.AccessToken)'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'DeveloperAutomation ECR'
    imageSource: 'imagename'
    sourceImageName: 'azure-devops-janitor-api'
    repositoryName: 'dfds.developerautomation-xavgy.azure-devops-janitor'
    pushTag: '$(Build.BuildId)'