apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-devops-janitor
  description: Handles Azure DevOps setup
  tags:
    - net
  annotations:
    'backstage.io/kubernetes-label-selector': 'project=developerautomation'
spec:
  type: service
  lifecycle: production
  owner: guest
  
