version: '3.9'

services:
  azuredevopsjanitor.host.api:
    image: azure-devops-janitor-api
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.Api/Dockerfile
  azuredevopsjanitor.host.eventconsumer:  
    image: azure-devops-janitor-event-consumer
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventConsumer/Dockerfile
  azuredevopsjanitor.host.eventforwarder:
    image: azure-devops-janitor-event-forwarder
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventForwarder/Dockerfile