version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=local"
  azuredevopsjanitor.host.api:
    image: azure-devops-janitor-api
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.Api/Dockerfile
  azuredevopsjanitor.host.eventconsumer:  
    image: azure-devops-janitor-event-consumer
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventConsumer/Dockerfile