version: '3.9'

services:
  azuredevopsjanitor.host.api:
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.Api/Dockerfile
  azuredevopsjanitor.host.eventconsumer:
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventConsumer/Dockerfile
  azuredevopsjanitor.host.eventforwarder:
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventForwarder/Dockerfile