---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: developerautomation-xavgy-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: developerautomation-xavgy
      name: aws-creds
      key: key