apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-janitor-event-consumer
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation
    department: cloudengineering
    app: azure-devops-janitor-event-consumer
    component: azure-devops-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-janitor-event-consumer
  template:
    metadata:
      labels:
        app: azure-devops-janitor-event-consumer
        project: developerautomation
        department: cloudengineering
        logging_dfds_cloud_format_json: "true"
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      - name: azure-devops-janitor-event-consumer
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.azure-devops-janitor:azure-devops-janitor-event-consumer-$(Build.BuildId)
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"