apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-janitor-event-consumer-deployment
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation
    department: cloudengineering
    component: azure-devops-janitor
    app: azure-devops-janitor-event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-janitor-event-consumer
  template:
    metadata:
      labels:
        project: developerautomation
        department: cloudengineering
        app: azure-devops-janitor-event-consumer
    spec:
      priorityClassName: selfservice
      containers:
      - name: azure-devops-janitor-event-consumer
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.azure-devops-janitor:azure-devops-janitor-event-consumer-#(Build.BuildId)
        env:
          - name: AdoClient__ClientSecret
            valueFrom:
              secretKeyRef:
                name: ado-credentials
                key: clientAccessToken
          - name: Kafka__Configuration__sasl.username
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: username
          - name: Kafka__Configuration__sasl.password
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: password
          - name: ConnectionStrings__ApplicationContext_Host
            valueFrom:
              secretKeyRef:
                name: azure-devops-janitor-rdspostgresql-conn
                key: endpoint
          - name: ConnectionStrings__ApplicationContext_Port
            valueFrom:
              secretKeyRef:
                name: azure-devops-janitor-rdspostgresql-conn
                key: port
          - name: ConnectionStrings__ApplicationContext_User
            valueFrom:
              secretKeyRef:
                name: azure-devops-janitor-rdspostgresql-conn
                key: username
          - name: ConnectionStrings__ApplicationContext_Password
            valueFrom:
              secretKeyRef:
                name: azure-devops-janitor-rdspostgresql-conn
                key: password
          - name: ConnectionStrings__ApplicationContext
            value: "User ID=$(ConnectionStrings__ApplicationContext_User);Password=$(ConnectionStrings__ApplicationContext_Password);Host=$(ConnectionStrings__ApplicationContext_Host);Port=$(ConnectionStrings__ApplicationContext_Port);Database=postgres"
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"