apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation   
type: Opaque
data:
  username: #(KAFKA_USERNAME)
  password: #(KAFKA_PASSWORD)
