apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: azure-devops-janitor-rds
  namespace: developerautomation-xavgy
  annotations:
    crossplane.io/external-name: azure-devops-janitor-rds
  labels:
    department: cloudengineering
    project: developerautomation
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: developerautomation-xavgy-provider-config
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "11"
    skipFinalSnapshotBeforeDeletion: true
    vpcSecurityGroupIDSelector:
      matchLabels:
        rdsinstance: azure-devops-janitor-rds
  writeConnectionSecretToRef:
    namespace: developerautomation-xavgy
    name: azure-devops-janitor-rdspostgresql-conn
