apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: azure-devops-janitor-rds
  namespace: developerautomation-xavgy
spec:
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "11"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: developerautomation-xavgy
    name: azure-devops-janitor-rdspostgresql-conn