apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: sequ-ns
  namespace: sequoiia
spec:
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "11"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: sequoiia
    name: aws-rdspostgresql-conn